channels:
  - numba
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.22
  - scipy>=1.10
  - numba>=0.59.1
  - pandas>=0.20.0
  - flake8>=3.7.7
  - flake8-docstrings>=1.5.0
  - black>=22.1.0
  - pytest-cov>=2.10.0
  - dask>=1.2.2
  - distributed>=1.28.1
  - jupyterlab>=3.0
  - matplotlib>=3.3.0
  - lxml>=4.5.2
  - twine>=3.2.0
  - sphinx>=3.5.3
  - pydata-sphinx-theme>=0.5.2
  - scikit-learn>=0.21.3
  - numpydoc>=1.1.0
  - python-build>=0.7.0
  - pytest-check-links>=0.7.1
  - isort>=5.11.0
  - jupyterlab-myst>=2.0.0
  - myst-nb>=1.0.0
  - polars>=1.14.0
